// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package engrave

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Metadata                   protoreflect.MessageDescriptor
	fd_Metadata_creatorWallet     protoreflect.FieldDescriptor
	fd_Metadata_generatedVia      protoreflect.FieldDescriptor
	fd_Metadata_modelUsed         protoreflect.FieldDescriptor
	fd_Metadata_assetId           protoreflect.FieldDescriptor
	fd_Metadata_assetType         protoreflect.FieldDescriptor
	fd_Metadata_promptAttribution protoreflect.FieldDescriptor
	fd_Metadata_ipOwnerName       protoreflect.FieldDescriptor
	fd_Metadata_ipOwnerWallet     protoreflect.FieldDescriptor
	fd_Metadata_usageRights       protoreflect.FieldDescriptor
	fd_Metadata_licenseExpiryDate protoreflect.FieldDescriptor
	fd_Metadata_createdOn         protoreflect.FieldDescriptor
	fd_Metadata_onChainRecord     protoreflect.FieldDescriptor
	fd_Metadata_blockHeight       protoreflect.FieldDescriptor
)

func init() {
	file_cifer_engrave_metadata_proto_init()
	md_Metadata = File_cifer_engrave_metadata_proto.Messages().ByName("Metadata")
	fd_Metadata_creatorWallet = md_Metadata.Fields().ByName("creatorWallet")
	fd_Metadata_generatedVia = md_Metadata.Fields().ByName("generatedVia")
	fd_Metadata_modelUsed = md_Metadata.Fields().ByName("modelUsed")
	fd_Metadata_assetId = md_Metadata.Fields().ByName("assetId")
	fd_Metadata_assetType = md_Metadata.Fields().ByName("assetType")
	fd_Metadata_promptAttribution = md_Metadata.Fields().ByName("promptAttribution")
	fd_Metadata_ipOwnerName = md_Metadata.Fields().ByName("ipOwnerName")
	fd_Metadata_ipOwnerWallet = md_Metadata.Fields().ByName("ipOwnerWallet")
	fd_Metadata_usageRights = md_Metadata.Fields().ByName("usageRights")
	fd_Metadata_licenseExpiryDate = md_Metadata.Fields().ByName("licenseExpiryDate")
	fd_Metadata_createdOn = md_Metadata.Fields().ByName("createdOn")
	fd_Metadata_onChainRecord = md_Metadata.Fields().ByName("onChainRecord")
	fd_Metadata_blockHeight = md_Metadata.Fields().ByName("blockHeight")
}

var _ protoreflect.Message = (*fastReflection_Metadata)(nil)

type fastReflection_Metadata Metadata

func (x *Metadata) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Metadata)(x)
}

func (x *Metadata) slowProtoReflect() protoreflect.Message {
	mi := &file_cifer_engrave_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Metadata_messageType fastReflection_Metadata_messageType
var _ protoreflect.MessageType = fastReflection_Metadata_messageType{}

type fastReflection_Metadata_messageType struct{}

func (x fastReflection_Metadata_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Metadata)(nil)
}
func (x fastReflection_Metadata_messageType) New() protoreflect.Message {
	return new(fastReflection_Metadata)
}
func (x fastReflection_Metadata_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Metadata
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Metadata) Descriptor() protoreflect.MessageDescriptor {
	return md_Metadata
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Metadata) Type() protoreflect.MessageType {
	return _fastReflection_Metadata_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Metadata) New() protoreflect.Message {
	return new(fastReflection_Metadata)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Metadata) Interface() protoreflect.ProtoMessage {
	return (*Metadata)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Metadata) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.CreatorWallet != "" {
		value := protoreflect.ValueOfString(x.CreatorWallet)
		if !f(fd_Metadata_creatorWallet, value) {
			return
		}
	}
	if x.GeneratedVia != "" {
		value := protoreflect.ValueOfString(x.GeneratedVia)
		if !f(fd_Metadata_generatedVia, value) {
			return
		}
	}
	if x.ModelUsed != "" {
		value := protoreflect.ValueOfString(x.ModelUsed)
		if !f(fd_Metadata_modelUsed, value) {
			return
		}
	}
	if x.AssetId != "" {
		value := protoreflect.ValueOfString(x.AssetId)
		if !f(fd_Metadata_assetId, value) {
			return
		}
	}
	if x.AssetType != "" {
		value := protoreflect.ValueOfString(x.AssetType)
		if !f(fd_Metadata_assetType, value) {
			return
		}
	}
	if x.PromptAttribution != "" {
		value := protoreflect.ValueOfString(x.PromptAttribution)
		if !f(fd_Metadata_promptAttribution, value) {
			return
		}
	}
	if x.IpOwnerName != "" {
		value := protoreflect.ValueOfString(x.IpOwnerName)
		if !f(fd_Metadata_ipOwnerName, value) {
			return
		}
	}
	if x.IpOwnerWallet != "" {
		value := protoreflect.ValueOfString(x.IpOwnerWallet)
		if !f(fd_Metadata_ipOwnerWallet, value) {
			return
		}
	}
	if x.UsageRights != "" {
		value := protoreflect.ValueOfString(x.UsageRights)
		if !f(fd_Metadata_usageRights, value) {
			return
		}
	}
	if x.LicenseExpiryDate != "" {
		value := protoreflect.ValueOfString(x.LicenseExpiryDate)
		if !f(fd_Metadata_licenseExpiryDate, value) {
			return
		}
	}
	if x.CreatedOn != "" {
		value := protoreflect.ValueOfString(x.CreatedOn)
		if !f(fd_Metadata_createdOn, value) {
			return
		}
	}
	if x.OnChainRecord != "" {
		value := protoreflect.ValueOfString(x.OnChainRecord)
		if !f(fd_Metadata_onChainRecord, value) {
			return
		}
	}
	if x.BlockHeight != int32(0) {
		value := protoreflect.ValueOfInt32(x.BlockHeight)
		if !f(fd_Metadata_blockHeight, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Metadata) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "cifer.engrave.Metadata.creatorWallet":
		return x.CreatorWallet != ""
	case "cifer.engrave.Metadata.generatedVia":
		return x.GeneratedVia != ""
	case "cifer.engrave.Metadata.modelUsed":
		return x.ModelUsed != ""
	case "cifer.engrave.Metadata.assetId":
		return x.AssetId != ""
	case "cifer.engrave.Metadata.assetType":
		return x.AssetType != ""
	case "cifer.engrave.Metadata.promptAttribution":
		return x.PromptAttribution != ""
	case "cifer.engrave.Metadata.ipOwnerName":
		return x.IpOwnerName != ""
	case "cifer.engrave.Metadata.ipOwnerWallet":
		return x.IpOwnerWallet != ""
	case "cifer.engrave.Metadata.usageRights":
		return x.UsageRights != ""
	case "cifer.engrave.Metadata.licenseExpiryDate":
		return x.LicenseExpiryDate != ""
	case "cifer.engrave.Metadata.createdOn":
		return x.CreatedOn != ""
	case "cifer.engrave.Metadata.onChainRecord":
		return x.OnChainRecord != ""
	case "cifer.engrave.Metadata.blockHeight":
		return x.BlockHeight != int32(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cifer.engrave.Metadata"))
		}
		panic(fmt.Errorf("message cifer.engrave.Metadata does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Metadata) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "cifer.engrave.Metadata.creatorWallet":
		x.CreatorWallet = ""
	case "cifer.engrave.Metadata.generatedVia":
		x.GeneratedVia = ""
	case "cifer.engrave.Metadata.modelUsed":
		x.ModelUsed = ""
	case "cifer.engrave.Metadata.assetId":
		x.AssetId = ""
	case "cifer.engrave.Metadata.assetType":
		x.AssetType = ""
	case "cifer.engrave.Metadata.promptAttribution":
		x.PromptAttribution = ""
	case "cifer.engrave.Metadata.ipOwnerName":
		x.IpOwnerName = ""
	case "cifer.engrave.Metadata.ipOwnerWallet":
		x.IpOwnerWallet = ""
	case "cifer.engrave.Metadata.usageRights":
		x.UsageRights = ""
	case "cifer.engrave.Metadata.licenseExpiryDate":
		x.LicenseExpiryDate = ""
	case "cifer.engrave.Metadata.createdOn":
		x.CreatedOn = ""
	case "cifer.engrave.Metadata.onChainRecord":
		x.OnChainRecord = ""
	case "cifer.engrave.Metadata.blockHeight":
		x.BlockHeight = int32(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cifer.engrave.Metadata"))
		}
		panic(fmt.Errorf("message cifer.engrave.Metadata does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Metadata) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "cifer.engrave.Metadata.creatorWallet":
		value := x.CreatorWallet
		return protoreflect.ValueOfString(value)
	case "cifer.engrave.Metadata.generatedVia":
		value := x.GeneratedVia
		return protoreflect.ValueOfString(value)
	case "cifer.engrave.Metadata.modelUsed":
		value := x.ModelUsed
		return protoreflect.ValueOfString(value)
	case "cifer.engrave.Metadata.assetId":
		value := x.AssetId
		return protoreflect.ValueOfString(value)
	case "cifer.engrave.Metadata.assetType":
		value := x.AssetType
		return protoreflect.ValueOfString(value)
	case "cifer.engrave.Metadata.promptAttribution":
		value := x.PromptAttribution
		return protoreflect.ValueOfString(value)
	case "cifer.engrave.Metadata.ipOwnerName":
		value := x.IpOwnerName
		return protoreflect.ValueOfString(value)
	case "cifer.engrave.Metadata.ipOwnerWallet":
		value := x.IpOwnerWallet
		return protoreflect.ValueOfString(value)
	case "cifer.engrave.Metadata.usageRights":
		value := x.UsageRights
		return protoreflect.ValueOfString(value)
	case "cifer.engrave.Metadata.licenseExpiryDate":
		value := x.LicenseExpiryDate
		return protoreflect.ValueOfString(value)
	case "cifer.engrave.Metadata.createdOn":
		value := x.CreatedOn
		return protoreflect.ValueOfString(value)
	case "cifer.engrave.Metadata.onChainRecord":
		value := x.OnChainRecord
		return protoreflect.ValueOfString(value)
	case "cifer.engrave.Metadata.blockHeight":
		value := x.BlockHeight
		return protoreflect.ValueOfInt32(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cifer.engrave.Metadata"))
		}
		panic(fmt.Errorf("message cifer.engrave.Metadata does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Metadata) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "cifer.engrave.Metadata.creatorWallet":
		x.CreatorWallet = value.Interface().(string)
	case "cifer.engrave.Metadata.generatedVia":
		x.GeneratedVia = value.Interface().(string)
	case "cifer.engrave.Metadata.modelUsed":
		x.ModelUsed = value.Interface().(string)
	case "cifer.engrave.Metadata.assetId":
		x.AssetId = value.Interface().(string)
	case "cifer.engrave.Metadata.assetType":
		x.AssetType = value.Interface().(string)
	case "cifer.engrave.Metadata.promptAttribution":
		x.PromptAttribution = value.Interface().(string)
	case "cifer.engrave.Metadata.ipOwnerName":
		x.IpOwnerName = value.Interface().(string)
	case "cifer.engrave.Metadata.ipOwnerWallet":
		x.IpOwnerWallet = value.Interface().(string)
	case "cifer.engrave.Metadata.usageRights":
		x.UsageRights = value.Interface().(string)
	case "cifer.engrave.Metadata.licenseExpiryDate":
		x.LicenseExpiryDate = value.Interface().(string)
	case "cifer.engrave.Metadata.createdOn":
		x.CreatedOn = value.Interface().(string)
	case "cifer.engrave.Metadata.onChainRecord":
		x.OnChainRecord = value.Interface().(string)
	case "cifer.engrave.Metadata.blockHeight":
		x.BlockHeight = int32(value.Int())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cifer.engrave.Metadata"))
		}
		panic(fmt.Errorf("message cifer.engrave.Metadata does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Metadata) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "cifer.engrave.Metadata.creatorWallet":
		panic(fmt.Errorf("field creatorWallet of message cifer.engrave.Metadata is not mutable"))
	case "cifer.engrave.Metadata.generatedVia":
		panic(fmt.Errorf("field generatedVia of message cifer.engrave.Metadata is not mutable"))
	case "cifer.engrave.Metadata.modelUsed":
		panic(fmt.Errorf("field modelUsed of message cifer.engrave.Metadata is not mutable"))
	case "cifer.engrave.Metadata.assetId":
		panic(fmt.Errorf("field assetId of message cifer.engrave.Metadata is not mutable"))
	case "cifer.engrave.Metadata.assetType":
		panic(fmt.Errorf("field assetType of message cifer.engrave.Metadata is not mutable"))
	case "cifer.engrave.Metadata.promptAttribution":
		panic(fmt.Errorf("field promptAttribution of message cifer.engrave.Metadata is not mutable"))
	case "cifer.engrave.Metadata.ipOwnerName":
		panic(fmt.Errorf("field ipOwnerName of message cifer.engrave.Metadata is not mutable"))
	case "cifer.engrave.Metadata.ipOwnerWallet":
		panic(fmt.Errorf("field ipOwnerWallet of message cifer.engrave.Metadata is not mutable"))
	case "cifer.engrave.Metadata.usageRights":
		panic(fmt.Errorf("field usageRights of message cifer.engrave.Metadata is not mutable"))
	case "cifer.engrave.Metadata.licenseExpiryDate":
		panic(fmt.Errorf("field licenseExpiryDate of message cifer.engrave.Metadata is not mutable"))
	case "cifer.engrave.Metadata.createdOn":
		panic(fmt.Errorf("field createdOn of message cifer.engrave.Metadata is not mutable"))
	case "cifer.engrave.Metadata.onChainRecord":
		panic(fmt.Errorf("field onChainRecord of message cifer.engrave.Metadata is not mutable"))
	case "cifer.engrave.Metadata.blockHeight":
		panic(fmt.Errorf("field blockHeight of message cifer.engrave.Metadata is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cifer.engrave.Metadata"))
		}
		panic(fmt.Errorf("message cifer.engrave.Metadata does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Metadata) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "cifer.engrave.Metadata.creatorWallet":
		return protoreflect.ValueOfString("")
	case "cifer.engrave.Metadata.generatedVia":
		return protoreflect.ValueOfString("")
	case "cifer.engrave.Metadata.modelUsed":
		return protoreflect.ValueOfString("")
	case "cifer.engrave.Metadata.assetId":
		return protoreflect.ValueOfString("")
	case "cifer.engrave.Metadata.assetType":
		return protoreflect.ValueOfString("")
	case "cifer.engrave.Metadata.promptAttribution":
		return protoreflect.ValueOfString("")
	case "cifer.engrave.Metadata.ipOwnerName":
		return protoreflect.ValueOfString("")
	case "cifer.engrave.Metadata.ipOwnerWallet":
		return protoreflect.ValueOfString("")
	case "cifer.engrave.Metadata.usageRights":
		return protoreflect.ValueOfString("")
	case "cifer.engrave.Metadata.licenseExpiryDate":
		return protoreflect.ValueOfString("")
	case "cifer.engrave.Metadata.createdOn":
		return protoreflect.ValueOfString("")
	case "cifer.engrave.Metadata.onChainRecord":
		return protoreflect.ValueOfString("")
	case "cifer.engrave.Metadata.blockHeight":
		return protoreflect.ValueOfInt32(int32(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cifer.engrave.Metadata"))
		}
		panic(fmt.Errorf("message cifer.engrave.Metadata does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Metadata) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in cifer.engrave.Metadata", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Metadata) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Metadata) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Metadata) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Metadata) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Metadata)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.CreatorWallet)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.GeneratedVia)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ModelUsed)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.AssetId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.AssetType)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.PromptAttribution)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.IpOwnerName)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.IpOwnerWallet)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.UsageRights)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.LicenseExpiryDate)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.CreatedOn)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.OnChainRecord)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.BlockHeight != 0 {
			n += 1 + runtime.Sov(uint64(x.BlockHeight))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Metadata)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.BlockHeight != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.BlockHeight))
			i--
			dAtA[i] = 0x68
		}
		if len(x.OnChainRecord) > 0 {
			i -= len(x.OnChainRecord)
			copy(dAtA[i:], x.OnChainRecord)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.OnChainRecord)))
			i--
			dAtA[i] = 0x62
		}
		if len(x.CreatedOn) > 0 {
			i -= len(x.CreatedOn)
			copy(dAtA[i:], x.CreatedOn)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.CreatedOn)))
			i--
			dAtA[i] = 0x5a
		}
		if len(x.LicenseExpiryDate) > 0 {
			i -= len(x.LicenseExpiryDate)
			copy(dAtA[i:], x.LicenseExpiryDate)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.LicenseExpiryDate)))
			i--
			dAtA[i] = 0x52
		}
		if len(x.UsageRights) > 0 {
			i -= len(x.UsageRights)
			copy(dAtA[i:], x.UsageRights)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.UsageRights)))
			i--
			dAtA[i] = 0x4a
		}
		if len(x.IpOwnerWallet) > 0 {
			i -= len(x.IpOwnerWallet)
			copy(dAtA[i:], x.IpOwnerWallet)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.IpOwnerWallet)))
			i--
			dAtA[i] = 0x42
		}
		if len(x.IpOwnerName) > 0 {
			i -= len(x.IpOwnerName)
			copy(dAtA[i:], x.IpOwnerName)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.IpOwnerName)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.PromptAttribution) > 0 {
			i -= len(x.PromptAttribution)
			copy(dAtA[i:], x.PromptAttribution)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.PromptAttribution)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.AssetType) > 0 {
			i -= len(x.AssetType)
			copy(dAtA[i:], x.AssetType)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.AssetType)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.AssetId) > 0 {
			i -= len(x.AssetId)
			copy(dAtA[i:], x.AssetId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.AssetId)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.ModelUsed) > 0 {
			i -= len(x.ModelUsed)
			copy(dAtA[i:], x.ModelUsed)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ModelUsed)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.GeneratedVia) > 0 {
			i -= len(x.GeneratedVia)
			copy(dAtA[i:], x.GeneratedVia)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.GeneratedVia)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.CreatorWallet) > 0 {
			i -= len(x.CreatorWallet)
			copy(dAtA[i:], x.CreatorWallet)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.CreatorWallet)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Metadata)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Metadata: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Metadata: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CreatorWallet", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.CreatorWallet = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field GeneratedVia", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.GeneratedVia = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ModelUsed", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ModelUsed = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AssetId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AssetType", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AssetType = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PromptAttribution", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.PromptAttribution = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field IpOwnerName", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.IpOwnerName = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field IpOwnerWallet", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.IpOwnerWallet = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field UsageRights", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.UsageRights = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 10:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field LicenseExpiryDate", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.LicenseExpiryDate = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 11:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CreatedOn", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.CreatedOn = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 12:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OnChainRecord", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.OnChainRecord = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 13:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
				}
				x.BlockHeight = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.BlockHeight |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: cifer/engrave/metadata.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatorWallet     string `protobuf:"bytes,1,opt,name=creatorWallet,proto3" json:"creatorWallet,omitempty"`
	GeneratedVia      string `protobuf:"bytes,2,opt,name=generatedVia,proto3" json:"generatedVia,omitempty"`
	ModelUsed         string `protobuf:"bytes,3,opt,name=modelUsed,proto3" json:"modelUsed,omitempty"`
	AssetId           string `protobuf:"bytes,4,opt,name=assetId,proto3" json:"assetId,omitempty"`
	AssetType         string `protobuf:"bytes,5,opt,name=assetType,proto3" json:"assetType,omitempty"`
	PromptAttribution string `protobuf:"bytes,6,opt,name=promptAttribution,proto3" json:"promptAttribution,omitempty"`
	IpOwnerName       string `protobuf:"bytes,7,opt,name=ipOwnerName,proto3" json:"ipOwnerName,omitempty"`
	IpOwnerWallet     string `protobuf:"bytes,8,opt,name=ipOwnerWallet,proto3" json:"ipOwnerWallet,omitempty"`
	UsageRights       string `protobuf:"bytes,9,opt,name=usageRights,proto3" json:"usageRights,omitempty"`
	LicenseExpiryDate string `protobuf:"bytes,10,opt,name=licenseExpiryDate,proto3" json:"licenseExpiryDate,omitempty"`
	CreatedOn         string `protobuf:"bytes,11,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	OnChainRecord     string `protobuf:"bytes,12,opt,name=onChainRecord,proto3" json:"onChainRecord,omitempty"`
	BlockHeight       int32  `protobuf:"varint,13,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cifer_engrave_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_cifer_engrave_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetCreatorWallet() string {
	if x != nil {
		return x.CreatorWallet
	}
	return ""
}

func (x *Metadata) GetGeneratedVia() string {
	if x != nil {
		return x.GeneratedVia
	}
	return ""
}

func (x *Metadata) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *Metadata) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *Metadata) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *Metadata) GetPromptAttribution() string {
	if x != nil {
		return x.PromptAttribution
	}
	return ""
}

func (x *Metadata) GetIpOwnerName() string {
	if x != nil {
		return x.IpOwnerName
	}
	return ""
}

func (x *Metadata) GetIpOwnerWallet() string {
	if x != nil {
		return x.IpOwnerWallet
	}
	return ""
}

func (x *Metadata) GetUsageRights() string {
	if x != nil {
		return x.UsageRights
	}
	return ""
}

func (x *Metadata) GetLicenseExpiryDate() string {
	if x != nil {
		return x.LicenseExpiryDate
	}
	return ""
}

func (x *Metadata) GetCreatedOn() string {
	if x != nil {
		return x.CreatedOn
	}
	return ""
}

func (x *Metadata) GetOnChainRecord() string {
	if x != nil {
		return x.OnChainRecord
	}
	return ""
}

func (x *Metadata) GetBlockHeight() int32 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

var File_cifer_engrave_metadata_proto protoreflect.FileDescriptor

var file_cifer_engrave_metadata_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x63, 0x69, 0x66, 0x65, 0x72, 0x2f, 0x65, 0x6e, 0x67, 0x72, 0x61, 0x76, 0x65, 0x2f,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x63, 0x69, 0x66, 0x65, 0x72, 0x2e, 0x65, 0x6e, 0x67, 0x72, 0x61, 0x76, 0x65, 0x22, 0xd6, 0x03,
	0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x6f, 0x72, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x56, 0x69, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x64, 0x56, 0x69, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x55, 0x73, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x55, 0x73,
	0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x70, 0x72,
	0x6f, 0x6d, 0x70, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x70, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69,
	0x70, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x70,
	0x4f, 0x77, 0x6e, 0x65, 0x72, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x69, 0x70, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x75, 0x73, 0x61, 0x67, 0x65, 0x52, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73, 0x61, 0x67, 0x65, 0x52, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6c,
	0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x4f, 0x6e, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x4f, 0x6e, 0x12, 0x24,
	0x0a, 0x0d, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x97, 0x01, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x63,
	0x69, 0x66, 0x65, 0x72, 0x2e, 0x65, 0x6e, 0x67, 0x72, 0x61, 0x76, 0x65, 0x42, 0x0d, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1e, 0x63,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x63, 0x69, 0x66, 0x65, 0x72, 0x2f, 0x65, 0x6e, 0x67, 0x72, 0x61, 0x76, 0x65, 0xa2, 0x02, 0x03,
	0x43, 0x45, 0x58, 0xaa, 0x02, 0x0d, 0x43, 0x69, 0x66, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x67, 0x72,
	0x61, 0x76, 0x65, 0xca, 0x02, 0x0d, 0x43, 0x69, 0x66, 0x65, 0x72, 0x5c, 0x45, 0x6e, 0x67, 0x72,
	0x61, 0x76, 0x65, 0xe2, 0x02, 0x19, 0x43, 0x69, 0x66, 0x65, 0x72, 0x5c, 0x45, 0x6e, 0x67, 0x72,
	0x61, 0x76, 0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x0e, 0x43, 0x69, 0x66, 0x65, 0x72, 0x3a, 0x3a, 0x45, 0x6e, 0x67, 0x72, 0x61, 0x76, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cifer_engrave_metadata_proto_rawDescOnce sync.Once
	file_cifer_engrave_metadata_proto_rawDescData = file_cifer_engrave_metadata_proto_rawDesc
)

func file_cifer_engrave_metadata_proto_rawDescGZIP() []byte {
	file_cifer_engrave_metadata_proto_rawDescOnce.Do(func() {
		file_cifer_engrave_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_cifer_engrave_metadata_proto_rawDescData)
	})
	return file_cifer_engrave_metadata_proto_rawDescData
}

var file_cifer_engrave_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cifer_engrave_metadata_proto_goTypes = []interface{}{
	(*Metadata)(nil), // 0: cifer.engrave.Metadata
}
var file_cifer_engrave_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cifer_engrave_metadata_proto_init() }
func file_cifer_engrave_metadata_proto_init() {
	if File_cifer_engrave_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cifer_engrave_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cifer_engrave_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cifer_engrave_metadata_proto_goTypes,
		DependencyIndexes: file_cifer_engrave_metadata_proto_depIdxs,
		MessageInfos:      file_cifer_engrave_metadata_proto_msgTypes,
	}.Build()
	File_cifer_engrave_metadata_proto = out.File
	file_cifer_engrave_metadata_proto_rawDesc = nil
	file_cifer_engrave_metadata_proto_goTypes = nil
	file_cifer_engrave_metadata_proto_depIdxs = nil
}
